# This is a basic workflow to help you get started with Actions

name: Latest-Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build zip
        run: |
          cp build.py ./community-vl3rotax915/build.py
          cd community-vl3rotax915
          python3 build.py
          cd ..
          zip -r latest.zip community-vl3rotax915
          cp latest.zip /data/915/latest.zip
          rm latest.zip
